appName: Dominator
serviceDomain: DM
serverPort: 15000
apiVersion: V1
webRoot: webroot

database:
  driverClass: org.postgresql.Driver
  dialect: POSTGRES
  username: dominator
  password: w0rld
  url: jdbc:postgresql://localhost:5432/dominator
  schema: dominator
